version: '3'

services:
  webapiapplication:
    container_name: webapiapplication
    image: dotnetserver
    build:
      context: ./server
      dockerfile: .docker/Dockerfile
    ports:
      - "5001:80"
    networks:
      - webapi-network

  node:
    container_name: nodeapp
    image: angularfrontend
    build:
      context: ./client
      dockerfile: .docker/Dockerfile
    environment:
      - NODE_ENV=development
    ports:
      - "8080:80"
    networks:
      - webapi-network

  mongodb:
    container_name: mongodbKinderkultur
    image: mongo
    env_file: .env
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
    networks:
      - webapi-network
    ports:
      - "27017:27017"

networks:
  webapi-network:
    driver: bridge