version: '2'

services:
  webapiapplication:
    container_name: webapiapplication
    image: dotnetserver
    build:
      context: ./server
      dockerfile: .docker/Dockerfile
    ports:
      - "5000:80"
    networks:
      - webapi-network

  node:
    container_name: nodeapp
    image: angularfrontend
    build:
      context: ./client
      dockerfile: .docker/Dockerfile
    environment:
      - NODE_ENV=development
    ports:
      - "8080:80"
    networks:
      - webapi-network

  mongodb:
    container_name: mongodb
    image: mongo
    networks:
      - webapi-network
    ports:
      - "27017:27017"

networks:
  webapi-network:
    driver: bridge